### ISSUE TITLE
About potential input files

### ISSUE THREAD

**Issue by xiki-tempula** [wiederm/endstate_correction#41]
Hi, Thank you very much for  the package.
I'm very interested in this repo and wish to have a go with it.
I wonder if I could have some input files to test it? Thank you.

**Comment by wiederm** [comment]
Hi! 
Sure, I will provide some input files! We are currently in the process of setting up a better documentation and HOW-TO (which should be finished after the weekend). I will point you to the improved HOW-TO-USE tutorial with some input files as soon as it is online but latest on Monday.

**Comment by xiki-tempula** [comment]
@wiederm Great Thanks.

**Comment by wiederm** [comment]
The documentation outlines now how to do an endstate correction for 1-octanol (in a waterbox) with FEP and NEQ:
https://wiederm.github.io/endstate_correction/getting_started.html#a-typical-neq-workflow

**Comment by xiki-tempula** [comment]
Thanks for the documentation. It might be good to add the imports to the top of the code block

```
from openmm.app.charmmparameterset import CharmmParameterSet
from openmm.app.charmmpsffile import CharmmPsfFile
from openmm.app.pdbfile import PDBFile
```

And set the location of the 1-octanol explicitly so people know where to find the files
 
```
parameter_base='endstate_correction/data/jctc_data'
system_name='1_octanol'
```

Then from

```
psf = CharmmPsfFile(f"{parameter_base}/{system_name}/charmm-gui/openmm/step3_input.psf")
pdb = PDBFile(f"{parameter_base}/{system_name}/charmm-gui/openmm/step3_input.pdb")
params = CharmmParameterSet(
    f"{parameter_base}/{system_name}/charmm-gui/unk/unk.rtf",
    f"{parameter_base}/{system_name}/charmm-gui/unk/unk.prm",
    f"{parameter_base}/toppar/top_all36_cgenff.rtf",
    f"{parameter_base}/toppar/par_all36_cgenff.prm",
    f"{parameter_base}/toppar/toppar_water_ions.str",
)
```

I wonder how do I get `ml_atoms = [atom.index for atom in chains[0].atoms()]`? Thanks.
