### ISSUE TITLE
The interplay between perform_endstate_correction and return_endstate_correction

### ISSUE THREAD

**Issue by xiki-tempula** [wiederm/endstate_correction#89]
Hi, I used to do

```python
r = perform_endstate_correction(fep_protocol)
mean, err = return_endstate_correction(r, direction='forw')
```

However, I cannot do this anymore as `perform_endstate_correction` returns `AllResults`, while `return_endstate_correction` expects `FEPResults` or `NEQResults`.

I wonder if I could have some help on this, please? Thank you.

**Comment by wiederm** [comment]
Hi @xiki-tempula ,

The signature of the function has changed. Can you please try:
`mean, err = return_endstate_correction(r.neq_results, direction='forw')`
